In [1]:
import torch

In [2]:
A = torch.randn(2, 3) * 10

In [3]:
A

tensor([[-13.5595,  -3.2755,  -3.3118],
        [  8.0832,  -4.3013,   3.1706]])

In [11]:
# Split A into 3 tensors:
# A_sign: contains the sign of each element in A
# A_mantissa: contains the mantissa of each element in A
# A_exponent: contains the exponent of each element in A
A_sign = torch.sign(A)
A_mantissa, A_exponent = torch.frexp(A)

In [12]:
A_sign

tensor([[-1., -1., -1.],
        [ 1., -1.,  1.]])

In [13]:
A_mantissa

tensor([[-0.8475, -0.8189, -0.8279],
        [ 0.5052, -0.5377,  0.7927]])

In [7]:
A_exponent

tensor([[4, 2, 2],
        [4, 3, 2]], dtype=torch.int32)